image: go1.4
git:
  path: github.com/cydev/vk
env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin
script:
  - go get -t .
  - go get github.com/axw/gocov/gocov
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go test .
